### PR TITLE
Warn user when he or she runs /remindEvent in a private conversation

### LINKED ISSUE #147: Handle nice the case where /remindEvent is triggered in a private conversation
When a user triggers the command `/remindEvent` in a private conversation, it fails with this log:

```
 SlackAPI.ERROR: API call failed in conversations_members.
 SlackAPI.ERROR: raw response: {"ok":false,"error":"channel_not_found"}
 ExceptionHandler.ERROR: Exception: in_array(): Argument #2 ($haystack) must be of type array, null given (type=0, at /home/clients/175ae9bd0cb7e0ef350895c48dd54a06/tools/slack-agenda-app/slackEvents.php:4
 ExceptionHandler.ERROR: Can't contact the user about this error (no userid).
```

and as far as user experience is concerned: it does nothing (ie: it does not display an error message).

It would be nice if we can send to the user a message explaining was is going on

### PR DESCRIPTION
**Pull request by gturri**
this fixes #147

### CODE REVIEW

File: slackEvents.php [hunk 1]
```diff
@@ -493,7 +493,11 @@ public function event_selection($channel_id, $trigger_id) {
         $app_id = $app_infos->user_id;
         $members = $this->api->conversations_members($channel_id);
 
-        if (!in_array($app_id, $members)) {
+        if (is_null($members) || !in_array($app_id, $members)) {
+            $text = is_null($members) ?
+                    "Vous avez probablement essayé d'excuter cette commande depuis une conversation privée, ce qui n'est pas supporté. Si vous pensez qu'il s'agit d'une erreur, vous pouvez contacter #c-outils-numeriques" :
```
Comment (vhouchouas) [inline slackEvents.php:498]: Maybe we can change the message to something less related to our NGO ?

> [...] vous pouvez contacter votre administrateur.

Or something like that?

**Comment by vhouchouas** [comment]
Thanks !
